// <auto-generated />
namespace EvilDuck.Platform.Core.PlaformMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_isExported_on_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_isExported_on_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201508191238584_adding_isExported_on_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
